### ISSUE TITLE
Correlation results

### ISSUE THREAD

**Issue by schr476** [fermilab-accelerator-ai/control-for-accelerators-in-hep#1]
Identify the top correlated variables to B:VIMIN & B:IMINER.

**Comment by dkafkes** [comment]
Top 5 positive/negative correlations:

![image](https://user-images.githubusercontent.com/39769360/84068904-4b7b2300-a98f-11ea-9f56-df816ba1cc3e.png)

**Comment by dkafkes** [comment]
![image](https://user-images.githubusercontent.com/39769360/84392874-844e0e80-abc0-11ea-9322-6651bc7ff0fe.png)

![image](https://user-images.githubusercontent.com/39769360/84392952-9e87ec80-abc0-11ea-8457-d3b6628c28bf.png)

**Comment by schr476** [comment]
The images do not include the variable in question.

**Comment by dkafkes** [comment]
Updated to include the variable in question.

![image](https://user-images.githubusercontent.com/39769360/84521705-04e13d80-ac9b-11ea-8f28-540313898249.png)

![image](https://user-images.githubusercontent.com/39769360/84521778-1d515800-ac9b-11ea-88f1-a0543d40dc51.png)

**Comment by schr476** [comment]
Please also use the rolling std variables in your correlation plots
